type: minio
endpoint: minio-map:9000 # Local: localhost:9000, Compose: minio-map:9000 
access_key: minioadmin
secret_key: minioadmin
bucket: map
secure: False
python_venv: /venv  # Compose: /venv Local: /Users/degn400/miniconda/envs/venv/
verbose: true
