## MODE 

# Install latest version of rocker image
FROM rocker/shiny:4.0.3

# Load general use libraries
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libssl-dev \
    libcurl4-openssl-dev \
    libcairo2-dev \
    libxt-dev \
    libssh2-1-dev \
    libhiredis-dev \
    libzmq3-dev \
    libxml2-dev \
    vim python3-venv

## restore from renv.lock ##

WORKDIR /srv/shiny-server/MODE

# only need these three to restore
COPY --chown=shiny:shiny .Rprofile .
COPY --chown=shiny:shiny renv/activate.R ./renv/activate.R
COPY --chown=shiny:shiny renv.lock .

# load package to be installed from source
COPY --chown=shiny:shiny local_packages ./local_packages

# set path to local packages for renv
ENV RENV_PATHS_LOCAL=/srv/shiny-server/MODE/local_packages

# everything must be done as shiny, otherwise shiny server will get permission denied
USER shiny

# 
RUN R -e 'renv::restore()'

# install rworker from github, this should install in the renv directory
RUN R -e "renv::install('./local_packages/rworker_0.1.2.tar.gz', repos=NULL, type='source')"

## Setup Python venv ##
USER root
COPY modeapp_requirements.txt .
RUN python3 -m venv /venv
RUN /venv/bin/pip install --upgrade pip
RUN /venv/bin/pip install -r modeapp_requirements.txt

# renv attempts to make a directory at root on startup as user shiny.  
# pre-make the directory and give the shiny user ownership.
RUN mkdir /Library
RUN chown shiny:shiny /Library

COPY --chown=shiny:shiny . .
